kind: Service
apiVersion: v1
metadata:
  name: pitchdeck-service
spec:
  selector:
    app: pitchdeck
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitchdeck-deployment
  labels:
    app: pitchdeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitchdeck
  template:
    metadata:
      labels:
        app: pitchdeck
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: pitchdeck
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
